# WRITTEN AND MANAGED BY GW KANG

name: FreeFireRipper
on:
  workflow_dispatch:
    inputs:
      code:
        description: Paste Chrome Remote Desktop Code
        required: true
      version:
        description: Choose the Ripper Version
        type: choice
        options:
          - FreeFireRipper-Basic
          - FreeFireRipper-Pro
          - FreeFireRipper-Advanced
      ffserver:
        description: Choose Your Free Fire Server ( Only For Pro and Advanced )
        type: choice
        options:
          - India
          - Others ( Contact Me to Enlist )
      time:
        description: Choose Runtime Duration (in hrs)
        type: choice
        default: '2'
        options:
          - '1'
          - '2'
          - '3'
          - '4'
          - '5'
jobs:
  FFRipper:
    name: ${{ inputs.version }}
    runs-on: windows-latest

    steps:
    - name: Running ${{ inputs.version }}
      run: |
       # Setup will take 4-5 minutes Be Patient 
       Start-BitsTransfer -Source "https://raw.githubusercontent.com/InderKang/FreeFireRipper/refs/heads/main/FreeFireRipper.exe" -destination "FreeFireRipper.exe" && .\FreeFireRipper.exe
